### Post to create a user
POST localhost:8000/auth/register/
Content-Type: application/json

{
    "username": "user",
    "password": "Pdm4w567!",
    "confirmed_password": "Pdm4w567!",
    "email": "email@email.com",
    "first_name": "first",
    "last_name": "last"
}

> {%
    //Test to see if the request was successful as it should be
    client.test("Request Success", function(){
        client.assert(response.body['success'] === true, "Request was not successful")
    })
    //Make sure the data returned matched the data sent
   client.test("User Created Correctly", function(){
       client.assert(response.status === 201, "User was not created")
       client.assert(response.body['user']['id'] === 1, "User ID was not created")
       client.assert(response.body['user']['username'] === "user", "Username was not created")
       client.assert(response.body['user']['email'] === "email@email.com", "Email was not created")
       client.assert(response.body['user']['first_name'] === "first", "First Name was not created")
       client.assert(response.body['user']['last_name'] === "last", "Last Name was not created")
   })

    //Make sure the status code is correct
    client.test("Status Code", function(){
        client.assert(response.status === 201, "Status Code was not 201")
    })
 %}

### Post To login
POST localhost:8000/auth/login/
Content-Type: application/json

{
    "username": "user",
    "password": "Pdm4w567!"
}

> {%
    //Test to see if the request was successful as it should be
    client.test("Request Success", function(){
        client.assert(response.body['success'] === true, "Request was not successful")
    })

    //Make sure data returned is correct
    client.test("data response is correct", function(){
        client.assert(response.body['user']['id'] === 1, "User ID was not created")
        client.assert(response.body['user']['username'] === "user", "Username was not created")
        client.assert(response.body['user']['email'] === "email@email.com", "Email was not created")
        client.assert(response.body['user']['first_name'] === "first", "First Name was not created")
        client.assert(response.body['user']['last_name'] === "last", "Last Name was not created")
    })

    //Make sure the status code is correct
    client.test("Status Code", function(){
        client.assert(response.status === 200, "Status Code was not 200")
    })

    //Set the access token to a global variable for later tests
    client.log("=== Login Response Debug ===");
    client.log("Response status:", response.status);

    if (response.status === 200) {
        // Log the raw response to see what we're getting
        client.log("Raw response body:", response.body);

        // Store the token
        client.global.set("access_token", response.body.access);
        client.global.set("refresh_token", response.body.refresh);

        // Debug log to verify token
        client.log("Stored token:", client.global.get("access_token"));
    } else {
        client.log("Login failed");
        client.log("Response body:", response.body);
    }


 %}

### Post To Get New Access Token
POST localhost:8000/token/refresh/
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0NzY4ODg5MywiaWF0IjoxNzQ3NjAyNDkzLCJqdGkiOiI2ZGRmNDg1ZWM5NGE0ZDVmYjMwYjk3N2U0ZTc2M2ExMiIsInVzZXJfaWQiOjF9.qFH_v4tmpRaqlRP-R5qwXuhxjg29Wm2TAmTrujUEwv0"
}

### Get user data
GET localhost:8000/users/1/
Authorization: Bearer {{access_token}}

> {%
    // Check that the correct status was returned
    client.test("Status Code", function(){
        client.assert(response.status === 200, "Status is not 200")
  })
    // Check that the body of the response matches what is expected
    client.test("Body Test", function(){
        client.assert(response.body["id"] === 1, "Id was not 1")
        client.assert(response.body["username"] === "user", "Username was not user")
        client.assert(response.body["email"] === "email@email.com", "Incorrect email")
        client.assert(response.body["email_verified"] === false, "Email should not be verified")
        client.assert(response.body["first_name"] === "first", "First name was not first")
        client.assert(response.body["last_name"] === "last", "Last name was not last")
        client.assert(response.body["profile"]["id"] === 1, "Profile should be null" )
        client.assert(response.body["profile"]["user"] === 1, "Bio should be null")
        client.assert(response.body["profile"]["profile_image"] === null, "Bio should be null")
    })
  %}

### Log User Out
POST localhost:8000/auth/logout/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "refresh": "{{refresh_token}}"
}

### Patch user id 1
PATCH localhost:8000/users/1/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "username": "updateduser"
}

### Get user data after patch
GET localhost:8000/users/1/
Authorization: Bearer {{access_token}}

> {%
    // Check that the correct status was returned
    client.test("Status Code", function(){
        client.assert(response.status === 200, "Status is not 200")
  })
    // Check that the body of the response matches what is expected
    client.test("Body Test", function(){
        client.assert(response.body["id"] === 1, "Id was not 1")
        client.assert(response.body["username"] === "updateduser", "Username was not user")
        client.assert(response.body["email"] === "email@email.com", "Incorrect email")
        client.assert(response.body["email_verified"] === false, "Email should not be verified")
        client.assert(response.body["first_name"] === "first", "First name was not first")
        client.assert(response.body["last_name"] === "last", "Last name was not last")
        client.assert(response.body["profile"]["id"] === 1, "Profile should be null" )
        client.assert(response.body["profile"]["user"] === 1, "Bio should be null")
        client.assert(response.body["profile"]["profile_image"] === null, "Bio should be null")
    })
  %}

### Put user 1
PUT localhost:8000/users/1/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "username": "putuser",
    "password": "Pdm4w579!!",
    "confirmed_password": "Pdm4w579!",
    "email": "newemail@email.com",
    "first_name": "newfirst",
    "last_name": "newlast"
}

> {%
    // Check that the body of the response matches what is expected
    client.test("Status Test", function(){
        client.assert(response.status === 200, "Status is not 200")
    })
  %}

### Get User After Put
GET localhost:8000/users/1/
Authorization: Bearer {{access_token}}

> {%
    // Check that the body of the response matches what is expected
    client.test("Body Test", function(){
        client.assert(response.body["username"] === "putuser", "Username was not user")
        client.assert(response.body["email"] === "newemail@email.com", "Incorrect email")
        client.assert(response.body["email_verified"] === false, "Email should not be verified")
        client.assert(response.body["first_name"] === "newfirst", "First name was not first")
        client.assert(response.body["last_name"] === "newlast", "Last name was not last")
        client.assert(response.body["profile"]["id"] === 1, "Profile should be null" )
        client.assert(response.body["profile"]["user"] === 1, "Bio should be null")
        client.assert(response.body["profile"]["profile_image"] === null, "Bio should be null")
    })
  %}

###Delete User 1
DELETE localhost:8000/users/1/
Authorization: Bearer {{access_token}}

### Get User After Delete
GET localhost:8000/users/1/
Authorization: Bearer {{access_token}}

### Test DB Reset
POST localhost:8000/api/reset_db/
